package com.model;

public enum QuestionTag {
    FIND_THE_ERROR, FILL_IN_THE_BLANK,
    SITUATION, WRITE_CODE, TRACE_OUTPUT,
    ANALYZE_COMPLIXITY, OPTIMIZE, COMPARE_APPROACH,
    DESIGN_DS, EXPLAIN_TERM
    
}
